name: ldsc3
channels:
- conda-forge
dependencies:
- python>=3.11,<3.14
- pip
- setuptools
- wheel
- python-dateutil>=2.8,<3
- pytz>=2020.1
- six>=1.16,<2
- tzdata
- pip:
  - bitarray>=3.0,<4
  - scipy>=1.15,<1.18
  - pandas>=2.3,<3.0
  - numpy>=2.1,<2.5
  - pyarrow>=21,<24
  - pyliftover>=0.4.1,<0.5
  - pytest>=8,<10
